# IDENTIFIABLE BASE:
# CREATE TABLE ${TABLE_NAME} (
#   ID              BIGINT(20)  NOT NULL AUTO_INCREMENT PRIMARY KEY
# )
#   COLLATE = 'utf8_general_ci'
#   ENGINE = InnoDB;

# TRACEABLE BASE:
# CREATE TABLE ${TABLE_NAME} (
#   ID          BIGINT(20)  NOT NULL AUTO_INCREMENT PRIMARY KEY,
#   CREATED_BY  VARCHAR(64) NOT NULL,
#   CREATED_AT  TIMESTAMP   NOT NULL,
#   MODIFIED_BY VARCHAR(64) NULL     DEFAULT NULL,
#   MODIFIED_AT TIMESTAMP   NULL     DEFAULT NULL
# )
#   COLLATE = 'utf8_general_ci'
#   ENGINE = InnoDB;

CREATE DATABASE hitec /*!40100 COLLATE 'utf8_general_ci' */;
USE hitec;

CREATE TABLE PERMISSION (
  ID              BIGINT(20)  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PERMISSION_TYPE VARCHAR(32) NOT NULL,
  CONSTRAINT UNQ_PERMISSION_PERMISSION_TYPE UNIQUE (PERMISSION_TYPE)
)
  COLLATE = 'utf8_general_ci'
  ENGINE = InnoDB;

CREATE TABLE USER (
  ID          BIGINT(20)  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  USERNAME    VARCHAR(32) NOT NULL,
  PASSWORD    VARCHAR(32) NOT NULL,
  ACTIVE      BOOLEAN     NOT NULL DEFAULT TRUE,
  CREATED_BY  VARCHAR(64) NOT NULL,
  CREATED_AT  TIMESTAMP   NOT NULL,
  MODIFIED_BY VARCHAR(64) NULL     DEFAULT NULL,
  MODIFIED_AT TIMESTAMP   NULL     DEFAULT NULL,
  CONSTRAINT UNQ_USER_USERNAME UNIQUE (USERNAME)
)
  COLLATE = 'utf8_general_ci'
  ENGINE = InnoDB;

INSERT INTO user (USERNAME, PASSWORD, ACTIVE, CREATED_BY, CREATED_AT, MODIFIED_BY, MODIFIED_AT)
VALUES ('admin', 'admin', b'1', 'admin', CURRENT_TIMESTAMP(), NULL, NULL);

CREATE TABLE USER_PERMISSION (
  USER       BIGINT(20) NOT NULL,
  PERMISSION BIGINT(20) NOT NULL,
  CONSTRAINT FK_USER_PERMISSION_USER_ID FOREIGN KEY (USER) REFERENCES USER (ID),
  CONSTRAINT FK_USER_PERMISSION_PERMISSION_ID FOREIGN KEY (PERMISSION) REFERENCES PERMISSION (ID),
  PRIMARY KEY (USER, PERMISSION)
)
  COLLATE = 'utf8_general_ci'
  ENGINE = InnoDB;

CREATE TABLE PRODUCT (
  ID          BIGINT(20)   NOT NULL AUTO_INCREMENT PRIMARY KEY,
  CODE        VARCHAR(16)  NOT NULL,
  NAME        VARCHAR(128) NOT NULL,
  PRICE       BIGINT(20)   NOT NULL,
  CREATED_BY  VARCHAR(64)  NOT NULL,
  CREATED_AT  TIMESTAMP    NOT NULL,
  MODIFIED_BY VARCHAR(64)  NULL     DEFAULT NULL,
  MODIFIED_AT TIMESTAMP    NULL     DEFAULT NULL,
  CONSTRAINT UNQ_PRODUCT_CODE UNIQUE (CODE)

)
  COLLATE = 'utf8_general_ci'
  ENGINE = InnoDB;

CREATE TABLE PRICE (
  ID          BIGINT(20)    NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PRODUCT     BIGINT(20)    NOT NULL,
  AMOUNT      DECIMAL(8, 2) NOT NULL,
  CREATED_BY  VARCHAR(64)   NOT NULL,
  CREATED_AT  TIMESTAMP     NOT NULL,
  MODIFIED_BY VARCHAR(64)   NULL     DEFAULT NULL,
  MODIFIED_AT TIMESTAMP     NULL     DEFAULT NULL,
  CONSTRAINT FK_PRICE_PRODUCT FOREIGN KEY (PRODUCT) REFERENCES PRODUCT (ID)
)
  COLLATE = 'utf8_general_ci'
  ENGINE = InnoDB;

ALTER TABLE PRODUCT
  ADD CONSTRAINT FK_PRODUCT_PRICE FOREIGN KEY (PRICE) REFERENCES PRICE (ID);

CREATE TABLE SALE_DEED (
  ID          BIGINT(20)    NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PRICE       BIGINT(20)    NOT NULL,
  QUANTITY    DECIMAL(8, 2) NOT NULL,
  BASE_PRICE  DECIMAL(8, 2) NOT NULL,
  REAL_PRICE  DECIMAL(8, 2) NOT NULL,
  CREATED_BY  VARCHAR(64)   NOT NULL,
  CREATED_AT  TIMESTAMP     NOT NULL,
  MODIFIED_BY VARCHAR(64)   NULL     DEFAULT NULL,
  MODIFIED_AT TIMESTAMP     NULL     DEFAULT NULL,
  CONSTRAINT FK_SALE_DEED_PRICE FOREIGN KEY (PRICE) REFERENCES PRICE (ID)
)
  COLLATE = 'utf8_general_ci'
  ENGINE = InnoDB;

CREATE TABLE PRODUCT_REGISTRY (
  ID          BIGINT(20)    NOT NULL AUTO_INCREMENT PRIMARY KEY,
  PRODUCT     BIGINT(20)    NOT NULL,
  QUANTITY    DECIMAL(8, 2) NOT NULL,
  SOLD        DECIMAL(8, 2) NOT NULL,
  FINISHED_ON TIMESTAMP     NULL     DEFAULT NULL,
  CREATED_BY  VARCHAR(64)   NOT NULL,
  CREATED_AT  TIMESTAMP     NOT NULL,
  MODIFIED_BY VARCHAR(64)   NULL     DEFAULT NULL,
  MODIFIED_AT TIMESTAMP     NULL     DEFAULT NULL,
  CONSTRAINT FK_PRODUCT_REGISTRY_PRODUCT FOREIGN KEY (PRODUCT) REFERENCES PRODUCT (ID)
)
  COLLATE = 'utf8_general_ci'
  ENGINE = InnoDB;


CREATE TABLE CASH_REGISTER (
  ID           BIGINT(20)  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  OPENING_DATE TIMESTAMP   NOT NULL,
  CLOSING_DATE TIMESTAMP   NULL     DEFAULT NULL,
  CREATED_BY   VARCHAR(64) NOT NULL,
  CREATED_AT   TIMESTAMP   NOT NULL,
  MODIFIED_BY  VARCHAR(64) NULL     DEFAULT NULL,
  MODIFIED_AT  TIMESTAMP   NULL     DEFAULT NULL
)
  COLLATE = 'utf8_general_ci'
  ENGINE = InnoDB;

CREATE TABLE CASH_REGISTER_SALE_DEED (
  CASH_REGISTER BIGINT(20) NOT NULL,
  SALE_DEED     BIGINT(20) NOT NULL,
  CONSTRAINT FK_CASH_REGISTER_SALE_DEED_CASH_REGISTER FOREIGN KEY (CASH_REGISTER) REFERENCES CASH_REGISTER (ID),
  CONSTRAINT FK_CASH_REGISTER_SALE_DEED_SALE_DEED FOREIGN KEY (SALE_DEED) REFERENCES SALE_DEED (ID),
  PRIMARY KEY (CASH_REGISTER, SALE_DEED)
)
  COLLATE = 'utf8_general_ci'
  ENGINE = InnoDB;

CREATE TABLE ACCOUNT (
  ID            BIGINT(20)  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME          VARCHAR(64) NOT NULL,
  CASH_REGISTER BIGINT(20)  NOT NULL,
  CREATED_BY    VARCHAR(64) NOT NULL,
  CREATED_AT    TIMESTAMP   NOT NULL,
  MODIFIED_BY   VARCHAR(64) NULL     DEFAULT NULL,
  MODIFIED_AT   TIMESTAMP   NULL     DEFAULT NULL,
  CONSTRAINT FK_ACCOUNT_CASH_REGISTER FOREIGN KEY (CASH_REGISTER) REFERENCES CASH_REGISTER (ID)
)
  COLLATE = 'utf8_general_ci'
  ENGINE = InnoDB;

CREATE TABLE ACCOUNT_SALE_DEED (
  ACCOUNT   BIGINT(20) NOT NULL,
  SALE_DEED BIGINT(20) NOT NULL,
  CONSTRAINT FK_ACCOUNT_SALE_DEED_ACCOUNT FOREIGN KEY (ACCOUNT) REFERENCES ACCOUNT (ID),
  CONSTRAINT FK_ACCOUNT_SALE_DEED_SALE_DEED FOREIGN KEY (SALE_DEED) REFERENCES SALE_DEED (ID),
  PRIMARY KEY (ACCOUNT, SALE_DEED)
)
  COLLATE = 'utf8_general_ci'
  ENGINE = InnoDB;